services:
  - type: web
    name: sogileave
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: KTOR_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /health
    region: frankfurt